app = 'request-catcher'
primary_region = 'sjc'

[build]

[env]
PORT = '8080'
HOST = '0.0.0.0'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 512
